org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
neo_version=26.1.2.111
neo_version_range=[26.1.2.111,)
loader_version_range=[1,)

mod_id=jei_plus_plus
mod_name=JEI++
mod_license=ARR
mod_version=1.0.7-26.1.2
mod_group_id=com.lingmu0
mod_authors=lingmu0
mod_description=JEI navigation and bookmark improvements with optional server-side AE2 pattern creation.

jei_version=29.43.0.106
jei_version_range=[29.43.0.106,)
